### Weather Forecast

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,precision_score
from sklearn.preprocessing import StandardScaler

In [11]:
df=pd.read_csv("weather_forecast_data.csv")
df

Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0       23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1       27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2       25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3       23.622080  74.367758    7.050551    67.255282   982.632013     rain
4       20.591370  96.858822    4.643921    47.676444   980.825142  no rain
...           ...        ...         ...          ...          ...      ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181  no rain
2496    27.558479  46.481744   10.884915    39.715133  1008.590961  no rain
2497    28.108274  43.817178    2.897128    75.842952   999.119187  no rain
2498    14.789275  57.908105    2.374717     2.378743  1046.501875  no rain
2499    26.554356  97.101517   18.563084    81.357508  1001.729176  no rain

[2500 rows x 6 columns]

In [12]:
df.isna().sum()

Temperature    0
Humidity       0
Wind_Speed     0
Cloud_Cover    0
Pressure       0
Rain           0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder  
le = LabelEncoder()
df["Rain"] = le.fit_transform(df["Rain"])
df

Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure  Rain
0       23.720338  89.592641    7.335604    50.501694  1032.378759     1
1       27.879734  46.489704    5.952484     4.990053   992.614190     0
2       25.069084  83.072843    1.371992    14.855784  1007.231620     0
3       23.622080  74.367758    7.050551    67.255282   982.632013     1
4       20.591370  96.858822    4.643921    47.676444   980.825142     0
...           ...        ...         ...          ...          ...   ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181     0
2496    27.558479  46.481744   10.884915    39.715133  1008.590961     0
2497    28.108274  43.817178    2.897128    75.842952   999.119187     0
2498    14.789275  57.908105    2.374717     2.378743  1046.501875     0
2499    26.554356  97.101517   18.563084    81.357508  1001.729176     0

[2500 rows x 6 columns]

In [14]:
x=df[['Temperature','Humidity','Wind_Speed','Cloud_Cover','Pressure']]
x

Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure
0       23.720338  89.592641    7.335604    50.501694  1032.378759
1       27.879734  46.489704    5.952484     4.990053   992.614190
2       25.069084  83.072843    1.371992    14.855784  1007.231620
3       23.622080  74.367758    7.050551    67.255282   982.632013
4       20.591370  96.858822    4.643921    47.676444   980.825142
...           ...        ...         ...          ...          ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181
2496    27.558479  46.481744   10.884915    39.715133  1008.590961
2497    28.108274  43.817178    2.897128    75.842952   999.119187
2498    14.789275  57.908105    2.374717     2.378743  1046.501875
2499    26.554356  97.101517   18.563084    81.357508  1001.729176

[2500 rows x 5 columns]

In [15]:
y=df['Rain']
y

0       1
1       0
2       0
3       1
4       0
       ..
2495    0
2496    0
2497    0
2498    0
2499    0
Name: Rain, Length: 2500, dtype: int32

In [16]:
ss=StandardScaler()
ss.fit_transform(x)

array([[ 0.1554307 ,  1.26539348, -0.44481385,  0.02897213,  0.8947143 ],
       [ 0.72322527, -0.89507374, -0.6841429 , -1.53407371, -1.07457032],
       [ 0.33954662,  0.93859882, -1.47673073, -1.19524633, -0.35066253],
       ...,
       [ 0.75442305, -1.0290299 , -1.21282806,  0.89928899, -0.75241945],
       [-1.0637386 , -0.32274425, -1.3032236 , -1.6237562 ,  1.59414185],
       [ 0.54229936,  1.64176416,  1.49793905,  1.08868017, -0.62316338]])

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
print(x_train,x_test,y_train,y_test)

      Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure
1552    31.182692  48.748026   16.348359    62.103172  1039.862168
2290    23.360801  76.249067    3.422692    29.850618   987.404833
1398    32.182079  88.988213    3.177929    78.339475   996.865872
1775    14.279301  89.812581   19.789469    95.934640  1031.653350
2299    23.697667  68.480758    9.261765    22.519844  1038.225189
...           ...        ...         ...          ...          ...
1638    26.825253  91.686792    8.058946    78.792732  1039.223895
1095    28.974614  58.618211   13.531515    67.976388  1025.789614
1130    10.051616  30.573940    9.517521    54.450577   997.630125
1294    10.619226  32.810852   16.924988    79.125241  1011.754684
860     33.427926  91.082135    2.555987    55.678875  1047.366547

[1750 rows x 5 columns]       Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure
1447    27.726270  32.703594   18.296473    22.387709  1008.501313
1114    21.034354  46.943073   15.470

In [18]:
k=4
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [19]:
y_pred=knn.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,

In [20]:
y_test

1447    0
1114    0
1064    1
2287    0
1537    0
       ..
427     0
105     1
2044    1
121     1
821     0
Name: Rain, Length: 750, dtype: int32

In [21]:
acc_score=accuracy_score(y_pred,y_test)
acc_score

0.9666666666666667

In [22]:
cns_matrix=confusion_matrix(y_pred,y_test)
cns_matrix

array([[656,  19],
       [  6,  69]], dtype=int64)

In [23]:
pns_score=precision_score(y_pred,y_test)
pns_score

0.7840909090909091

In [28]:
new_data=np.array([[23.720338,89.592641,7.335604,50.501694,1032.378759]])
new= ss.transform(new_data)
predicted_prob = knn.predict(new)
print(f'Predicted Outcome: {predicted_prob[0]:.2f}')

Predicted Outcome: 0.00


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
